# Generated by Django 4.1.2 on 2023-05-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaracTipoCuenta',
            fields=[
                ('id_carac', models.AutoField(db_column='id_carac', primary_key=True, serialize=False)),
                ('nom_carac', models.CharField(max_length=25)),
                ('min_carac', models.IntegerField()),
                ('max_carac', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(db_column='id_cuenta', primary_key=True, serialize=False)),
                ('carac_desc', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
                ('info_ext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id_tipo_cuenta', models.AutoField(db_column='id_tipo_cuenta', primary_key=True, serialize=False)),
                ('nom_tipo_cuenta', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usu', models.AutoField(db_column='id_usu', primary_key=True, serialize=False)),
                ('nom_usu', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('pw_usu', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenCuenta',
            fields=[
                ('id_img', models.AutoField(db_column='id_img', primary_key=True, serialize=False)),
                ('img', models.ImageField(null=True, upload_to='ImagenesCuentas')),
                ('id_cuenta', models.ForeignKey(db_column='id_carac', on_delete=django.db.models.deletion.CASCADE, to='Shopy.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaCarac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('id_carac', models.ForeignKey(db_column='id_carac', on_delete=django.db.models.deletion.CASCADE, to='Shopy.caractipocuenta')),
                ('id_cuenta', models.ForeignKey(db_column='id_cuenta', on_delete=django.db.models.deletion.CASCADE, to='Shopy.cuenta')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='id_tipo_cuenta',
            field=models.ForeignKey(db_column='id_tipo_cuenta', on_delete=django.db.models.deletion.CASCADE, to='Shopy.tipocuenta'),
        ),
        migrations.CreateModel(
            name='ConexionTipoCarac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carac', models.ForeignKey(db_column='id_carac', on_delete=django.db.models.deletion.CASCADE, to='Shopy.caractipocuenta')),
                ('id_tipo_cuenta', models.ForeignKey(db_column='id_tipo_cuenta', on_delete=django.db.models.deletion.CASCADE, to='Shopy.tipocuenta')),
            ],
        ),
    ]
