# Generated by Django 4.1.2 on 2023-06-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocuenta',
            name='id_tipo_cuenta',
            field=models.IntegerField(db_column='id_tipo_cuenta', default=0, primary_key=True, serialize=False),
        ),
    ]
